/// Proje içinde kullanılan padding ler
const double paddingXXXXXS = 4;
const double paddingXXXXS = 8;
const double paddingXXXS = 12;
const double paddingXXS = 16;
const double paddingXS = 20;
const double paddingS = 24;
const double paddingM = 28;
const double paddingL = 32;
const double paddingXL = 36;
const double paddingXXL = 40;
const double paddingXXXL = 44;
const double paddingXXXXL = 48;
const double paddingXXXXXL = 52;
const double paddingXXXXXXL = 56;
const double paddingXXXXXXXL = 60;
const double paddingXXXXXXXXL = 64;

/// Proje içinde kullanılan radiusler
const double radiusXXXXXXS = 3;
const double radiusXXXXXS = 4;
const double radiusXXXXS = 5;
const double radiusXXXS = 6;
const double radiusXXS = 8;
const double radiusXS = 10;
const double radiusS = 12;
const double radiusM = 15;
const double radiusL = 20;
const double radiusXL = 25;
const double radiusXXL = 30;
const double radiusXXXL = 40;
const double radiusXXXXL = 50;
